[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
presale = "GMSMiCgJuzJNiMkUQcfQxnMB2qBaZDLzk7AgQFAj2uAo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
