[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
presale = "2DX5uvQ5U5jWWdGgGgffysjJhATjiGPCmNZPJDqmRwf4"

[programs.devnet]
presale = "2DX5uvQ5U5jWWdGgGgffysjJhATjiGPCmNZPJDqmRwf4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "F9s53ENR9nWMicTKk2PFaYkpX5pTiPr9zWKSjsgzXe3t"
